spring:
  data:
    mongodb:
      database: ${DB_DATABASE:customers}
      host: ${DB_HOST:mongo_db}
      port: ${DB_PORT:27017}

springdoc:
  api-docs:
    path: /customers-docs
  swagger-ui:
    operations-sorter: method
